[project]
name = "pysparker"
version = "0.1.1"
description = "Some utility functions for PySpark."
authors = [{ name = "Ben Du", email = "longendu@yahoo.com" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "MIT"
keywords = [
    "PySpark",
    "utils",
    "big data",
]
dependencies = [
    "loguru>=0.6.0",
    "datacompy[spark]>=0.19.1",
]

[project.urls]
Repository = "https://github.com/legendu-net/pysparker"

[dependency-groups]
dev = [
    "ruff>=0.11.7",
    "pyspark>=3.5.6",
    "pytest>=7.1.2",
    "deptry>=0.24.0",
    "ty>=0.0.8",
]

[tool.deptry.per_rule_ignores]
DEP004 = [
    "pyspark",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"