name: pre-release
on:
  push:
    branches: ["main"]
jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/legendu-net/icon/main/install_icon.sh | sudo bash -
          icon pt -ic
      - name: Build Package
        run: |
          ~/.local/bin/poetry build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: next
          prerelease: true
          title: "Development Build"
          files: |
            dist/*
