name: Test Code on macOS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev, main ]
jobs:
  test_code:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: 
          #- ubuntu-latest
          - macOS-latest
        python-version: 
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@latest
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/legendu-net/icon/main/install_icon.sh | sudo bash -
        icon docker -ic --user-to-docker ""
        icon pt -ic
        ~/.local/bin/poetry env use python3
        ~/.local/bin/poetry install
        brew install libmagic
        brew link libmagic
    - name: Test with pytest
      run: |
        ~/.local/bin/poetry run pytest
